frontend:
    resource: "@FrontendBundle/Resources/config/routing.yml"
    prefix:   /

database:
    resource: "@DatabaseBundle/Resources/config/routing.yml"
    prefix:   /database

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

#app:
#    resource: "@AppBundle/Controller/"
#    type:     annotation