frontend_homepage:
    path:     /
    defaults: { _controller: FrontendBundle:Default:index }

listar:
    path:     /gama/{gama}
    defaults: { _controller: FrontendBundle:Default:listar }

insertar:
    path:     /insertar
    defaults: { _controller: FrontendBundle:Default:insertar }

page:
    path:     /
    #defaults: { _controller: FrontendBundle:Default:insertar }